site_name: Data Science
docs_dir: 'docs/en'
site_url: https://datascience_careerera.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-jupyter

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate 
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

nav: 
  - Home: 'index.md'
  - 'Python Programming':
    - 'Introduction to Python Programming': 'python/intro.md'
    - 'Setting up a Development Environment': 'python/env.md'
    - 'Basic Python Concepts': 
      - 'Course': 'python/basic.md'
      - 'Basic python notebook' : python/notebooks/python_Basics_examples.ipynb
      - 'Python exercices notebook 1' : python/notebooks/Python_Problems_1_Solution.ipynb
      - 'Python exercices notebook 2' : python/notebooks/Python_Problems_solution_2.ipynb
    - 'Object Oriented Programming in Python': 
      - 'Course': 'python/oop.md'
      - 'OOP exercices notebook 1' : python/notebooks/OOP_Problems_1_solution.ipynb
      - 'OOP exercices notebook 2' : python/notebooks/OOP_Problems_2_solution.ipynb

    - 'File Input/Output (I/O) Operations': 
      - 'Course': 'python/io.md'
      - 'I/O Operations exercices notebook' : python/notebooks/oi_python.ipynb


  - 'Data Analysis tools in Python': 
      - 'Understanding & working with Numpy': 'python/numpy.md'
      - 'Numpy exercices notebook' : python/notebooks/NumPy_Problem_series_solution.ipynb
      - 'Understanding & working with Pandas': 'python/pd.md'
      - 'Pandas Course notebook' : python/notebooks/pandascourse.ipynb
      - 'Pandas exercices notebook' : python/notebooks/Pandas_problem_series_solution.ipynb
      - 'Understanding & working with Matplotlib' : 'python/plt.md'
      - 'Understanding & working with Seaborn' : 'python/sns.md'
      - 'Seaborn and Matplotlib Course notebook' : python/notebooks/Matplotlib_Seaborn_course.ipynb
      - 'Data Visualization exercices notebook' : python/notebooks/Seaborn_Matplotlib_Problem_series_solution.ipynb


  - 'Database Management Systems' :
    - 'Introduction to DBMS' : 'sql/01_sql_intro.md'
    - 'Relational DBMS' :
      - 'Introduction' : 
        - 'What is a Relational DBMS' : 'sql/02_db_kesako.md'
        - 'Basic Principals' :
            - 'Tables & Keys': 'sql/03_table.md'
            - 'SQL': 'sql/04_basics.md'
      - 'Installation':
        - 'Install MySQL on MacOS': 'sql/05_MacOS_install.md'
        - 'Install MySQL with docker': 'sql/06_b_docker_install.md'
      - 'CRUD (Create, Read, Update, Delete) operations':
        - 'Creating tables': 'sql/07_creating_tables.md'
        - 'Inserting Data': 'sql/08_insert.md'
        - 'Constraints': 'sql/09_constraints.md'
        - 'Update & Delete': 'sql/10_update_delete.md'
      - 'SQL Queries' :
        - 'Basic Queries': 'sql/11_queries.md'
        - 'More Queries': 'sql/13_queries_db.md'
      - 'Build a company database from scratch': 'sql/12_company_db_1.md'
      - 'Advanced SQL':
        - 'SQL Functions': 'sql/14_functions.md'
        - 'Wildcards & Unions': 'sql/15_Wildcards.md'
        - 'Joins': 'sql/17_joins.md'
        - 'Nested Queries': 'sql/18_Nested_Queries.md'
        - 'On Delete': 'sql/19_delete.md'
        - 'Triggers': 'sql/20_triggers.md'
        - 'ER DIagrams': 'sql/21_er_diagrams.md'
      - 'Python and SQLAlchemy': 
        - 'Introduction': 'sql/22_Python_SQLAlchemy.md'
        - 'Querying Data with Python': 'sql/23_python_query.md'
        - 'Object Relational Mapping in Python': 'sql/24_python_orm.md'
        - 'Updating and Deleting Data with Python': 'sql/25_python_update_delete.md'
        - 'Advanced Queries with Python': 'sql/26_python_queries.md'
        - 'Working with large dataset': 'sql/27_python_large_data.md'
        - 'SQLAlchemy and FastAPI': 'sql/28_python_fastapi.md'
        - 'SQLAlchemy and Docker': 'sql/29_python_docker_sql.md'
        - 'Python Wrap-up Projects': 'sql/30_python_projects.md'
  
    - 'NoSQL DBMS':
      - 'Introduction NoSQL': 'nosql/intro.md'
      - 'Redis': 'nosql/redis.md'
      - 'MongoDB': 'nosql/mongo.md'
      - 'Neo4j': 'nosql/neo4j.md'
      - 'ELK':
        - 'Introduction': 'nosql/intro_elk.md'
        - 'Elasticsearch': 'nosql/elastic.md'
        - 'elastic Notebook': nosql/python_elastic.ipynb
        - 'Logstash and Kibana': 'nosql/logstash.md'
        - 'Monitoring and Administration': 'nosql/monitoring_admin.md'


  - 'Machine/Deep Learning':
      - 'Machine Learning' : 
        - 'Introduction': 'ml/ml.md'
        - 'Evaluation Metrics': 'ml/eval.md'
        - 'Linear regression example notebook' : ml/notebooks/CODE_Regression_lineaire_simple.ipynb
        - 'AirBnB prediction project' : ml/notebooks/ModeleLineaire_AirBnB_SOL.ipynb
        - 'CART' : ml/notebooks/CARTCourse.ipynb
        - 'RandomForest regression and Kmeans clustering example notebook' : ml/notebooks/RandomForest_mini_exo.ipynb
        - 'Iris classification project with RandomForest' : ml/notebooks/RandomForestIRIS_SOL.ipynb
        - 'Image classification project with Knn and PCA' : ml/notebooks/TP_Classification_kppv-pca_SOL.ipynb
      - 'Deep Learning' : 
        - 'Introduction' : 'ml/dl.md'
        - 'Types of Deep Learning' : 'ml/dltypes.md'
        - 'Image classification project with MLP and CNN': ml/notebooks/MLP_+_CNN.ipynb
        - 'Sentiment Analysis project with RNN and LSTMs' : ml/notebooks/RNN_sentiment_analysis_problem.ipynb


  - 'Restful API':
    - 'Introduction' : 'api/api.md'


  - 'Docker for App Deployment':
    - 'Introduction': 'docker/docker_intro.md'
    - 'Setting up Docker': 'docker/docker_install.md'
    - 'Building a Docker Image for Python App': 'docker/docker_python_app.md'
    - 'Docker CLI Commands': 'docker/docker_commands.md'
    - 'Docker Volumes': 'docker/docker_volume.md'
    - 'Docker Network': 'docker/docker_network.md'
    - 'Docker-compose': 'docker/docker_compose.md'
    - 'Docker and HTTPS': 'docker/docker_https.md'
    - 'Docker Registeries': 'docker/docker_cloud_registery.md'
    - 'Best Practices': 'docker/docker_best_practice.md'


  - 'MLOps':
    - 'Introduction': 'mlops/intro_mlops.md'
    - 'DLaaS - Deep Learning as a Service': 'mlops/dlaas.md'