site_name: Data Science
docs_dir: 'docs/en'
site_url: https://datascience_careerera.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material

nav: 
  - Home: 'index.md'
  - 'Python Programming':
    - 'Introduction to Python Programming': 'intro.md'
    - 'Setting up a Development Environment': 'env.md'
    - 'Basic Python Concepts': 'basic.md'
    - 'Object Oriented Programming in Python': 'oop.md'
    - 'File Input/Output (I/O) Operations': 'io.md'
    - 'Python with Data Science tools': 
      - 'Numpy: Understanding & working with Numpy': 'numpy.md'
      - 'Pandas: Understanding & working with Pandas': 'pd.md'
  - 'SQL and Python for Data Analysis and Database Development': 
    - 'Introduction': 'sql/01_sql_intro.md' 
    - 'What is a Database': 'sql/02_db_kesako.md'
    - 'Tables & Keys': 'sql/03_table.md'
    - 'SQL Basic understanding': 'sql/04_basics.md'
    - 'Install MySQL on MacOS': 'sql/05_MacOS_install.md'
    - 'Install MySQL on Windows': 'sql/06_Windows_install.md'
    - 'Creating tables': 'sql/07_creating_tables.md'
    - 'Inserting Data': 'sql/08_insert.md'
    - 'Constraints': 'sql/09_constraints.md'
    - 'Update & Delete': 'sql/10_update_delete.md'
    - 'Basic Queries': 'sql/11_queries.md'
    - 'Build a company database from scratch': 'sql/12_company_db_1'
    - 'More Queries': 'sql/13_queries_db.md'
    - 'SQL Functions': 'sql/14_functions.md'
    - 'Wildcards & Unions': 'sql/15_Wildcards.md'
    #- 'Union': 'sql/16_unions.md'
    - 'Joins': 'sql/17_joins.md'
    - 'Nested Queries': 'sql/18_Nested_Queries.md'
    - 'On Delete': 'sql/19_delete.md'
    - 'Triggers': 'sql/20_triggers.md'
    - 'ER DIagrams': 'sql/21_er_diagrams.md'
    - 'Python and SQLAlchemy': 'sql/22_Python_SQLAlchemy.md'
    - 'Querying Data with Python': 'sql/23_python_query.md'

