site_name: Data Science
docs_dir: 'docs/en'
site_url: https://datascience_careerera.com/

theme:
  name: material

nav: 
  - Home: 'index.md'
  - 'Python Programming':
    - 'Introduction to Python Programming': 'intro.md'
    - 'Setting up a Development Environment': 'env.md'
    - 'Basic Python Concepts': 'basic.md'
    - 'Object Oriented Programming in Python': 'oop.md'
    - 'File Input/Output (I/O) Operations': 'io.md'
    - 'Python with Data Science tools': 
      - 'Numpy: Understanding & working with Numpy': 'numpy.md'
      - 'Pandas: Understanding & working with Pandas': 'pd.md'
  - 'SQL and Python for Data Analysis and Database Development': 
    - 'Introduction': 'sql/1_sql_intro.md' 
    - 'What is a Database': 'sql/2_db_kesako.md'
    - 'Tables & Keys': 'sql/3_table.md'

