site_name: Data Science
site_url: https://datascience_careerera.com/
nav: 
  - Home: 'index.md'
  - 'Python Programming':
    - 'Introduction to Python Programming': 'intro.md'
    - 'Setting up a Development Environment': 'env.md'
    - 'Basic Python Concepts': 'basic.md'
theme:
  name: material

