site_name: Data Science
docs_dir: '../../docs/fr'
site_url: https://datascience_careerera.com/

theme:
  name: material

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: French
      link: /fr/
      lang: fr

nav: 
  - Home: 'index.md'
  - 'Python Programming':
    - 'Introduction to Python Programming': 'intro.md'
    - 'Setting up a Development Environment': 'env.md'
    - 'Basic Python Concepts': 'basic.md'
    - 'Object Oriented Programming in Python': 'oop.md'
    - 'File Input/Output (I/O) Operations': 'io.md'
    - 'Working with Data in Python': 'data.md'
